### ISSUE TITLE
سلام خوبی

### ISSUE THREAD

**Issue by 82sina82** [PYRONstar/py#1]
مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکنید خیلی خوبه من بچه نیستم بزرگم بابامه

**Comment by PYRONstar** [comment]
> مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکنید خیلی خوبه من بچه نیستم بزرگم بابامه

mm

**Comment by PYRONstar** [comment]
> > مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکنید خیلی خوبه من بچه نیستم بزرگم بابامه
> 
> سلام دوست عزیز متوجه منطور شما نشدم

**Comment by 82sina82** [comment]
> > > مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکن خیلی خوبه من بچه نیستم بزرگم بابامه
> > 
> > 
> > سلام دوست عزیز متوجه منطور شما نشدم

داش من ک

**Comment by PYRONstar** [comment]
> > > > مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکن خیلی خوبه من بچه نیستم بزرگم بابامه
> > > 
> > > 
> > > سلام دوست عزیز متوجه منطور شما نشدم
> 
> داش من ک

بله شما ک

**Comment by 82sina82** [comment]
> > > > > مشکل داره درسته کار میکنه ایراد داره عالیه داغونه بهتر از این نمیشه اصلا تست نکن خیلی خوبه من بچه نیستم بزرگم بابامه
> > > > 
> > > > 
> > > > سلام دوست عزیز متوجه منطور شما نشدم
> > 
> > 
> > داش من ک
> 
> بله شما ک

بریز
